import "./globals.css";

// INTERNAL IMPORT
import { DuckProvider } from "@/context/Duck";
import { Navbar, Footer } from "@/components";

export const metadata = {
  title: "Duck Shipping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DuckProvider>
          <Navbar />
          {children}
        </DuckProvider>
          <Footer />
      </body>
    </html>
  );
}
